import { Lightbulb } from "lucide-react";

export default function AdminSuggestionsPage() {
  return (
    <div className="animate-scanza-fade-in max-w-2xl">
      <h1 className="mb-2 flex items-center gap-2 font-display text-2xl font-bold text-scanza-text">
        <Lightbulb size={22} className="text-scanza-primary" /> Suggestions Library
      </h1>
      <p className="mb-6 text-scanza-text-muted">
        Resume improvement suggestions are currently generated by a rule-based engine at{" "}
        <code className="rounded bg-scanza-bg px-1.5 py-0.5 text-xs">services/main-service/src/services/suggestions.service.ts</code>.
      </p>
      <div className="rounded-2xl border border-scanza-border bg-scanza-surface p-6">
        <p className="mb-2 text-sm font-medium text-scanza-text">Current rule categories:</p>
        <ul className="list-inside list-disc space-y-1.5 text-sm text-scanza-text-muted">
          <li>Contact Info completeness (email, LinkedIn, GitHub for technical roles)</li>
          <li>Impact & Wording (action verbs, quantified metrics)</li>
          <li>Overall Quality (derived from the scoring engine&apos;s explainable reasons)</li>
          <li>Education presence</li>
        </ul>
        <p className="mt-4 text-xs text-scanza-text-muted">
          A visual editor for adding/editing suggestion rules without touching code is a natural next iteration —
          the underlying data model (<code>Suggestion</code> in the Prisma schema) already supports it.
        </p>
      </div>
    </div>
  );
}
